version: "3.1"

services:
  agenda:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
    ports:
      - 9000:3000
    environment:
      MONGODB_URI: mongodb://root:root@db_agenda/agenda
    depends_on:
      - db_agenda
  db_agenda:
    build:
      context: .
      dockerfile: docker/mongodb/Dockerfile
    restart: always
    volumes:
      - mongodb_agenda:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: agenda

volumes:
  mongodb_agenda:
